server:
  port: 8085

spring:
  application:
    name: springboot-redisson
  redis:
    database: 2
    host:
    port: 6379
    password:
    # password: ENC(1083061FF4033F3397FED9C2AF4AED9F)
    pool:
      max-active: 100
      max-idle: 5
      max-wait: 60000